INSERT INTO hotel
VALUES (50, 1, 1, 1, 1, 1);

INSERT ALL
    INTO operator VALUES (1, 'Residencia estudiantil1', 'Residencia estudiantil')
    INTO operator_service VALUES ('Residencia estudiantil1',1,1,1)
    INTO operator_spec VALUES ('Residencia estudiantil1', 100, 2, 'coordenadas1',1)
    INTO student_res_spec VALUES ('Residencia estudiantil1', 1,1,1,0)
    INTO operator VALUES (2, 'Residencia estudiantil2', 'Residencia estudiantil')
    INTO operator_service VALUES ('Residencia estudiantil2',1,1,1)
    INTO operator_spec VALUES ('Residencia estudiantil2', 98, 3, 'coordenadas2',0)
    INTO student_res_spec VALUES ('Residencia estudiantil2', 1,1,0,1)
    INTO operator VALUES (3, 'Residencia estudiantil3', 'Residencia estudiantil')
    INTO operator_service VALUES ('Residencia estudiantil3',1,1,1)
    INTO operator_spec VALUES ('Residencia estudiantil3', 99, 2, 'coordenadas3',1)
    INTO student_res_spec VALUES ('Residencia estudiantil3', 1,1,1,1)
    INTO operator VALUES (4, 'Residencia estudiantil4', 'Residencia estudiantil')
    INTO operator_service VALUES ('Residencia estudiantil4',1,1,1)
    INTO operator_spec VALUES ('Residencia estudiantil4', 120, 4, 'coordenadas4',0)
    INTO student_res_spec VALUES ('Residencia estudiantil4', 1,0,1,1)
    INTO operator VALUES (5, 'Residencia estudiantil5', 'Residencia estudiantil')
    INTO operator_service VALUES ('Residencia estudiantil5',1,1,1)
    INTO operator_spec VALUES ('Residencia estudiantil5', 100, 2, 'coordenadas5',1)
    INTO student_res_spec VALUES ('Residencia estudiantil5', 0,1,1,1)
    INTO operator VALUES (6, 'Residencia no-estudiantil1', 'Residencia no-estudiantil')
    INTO operator_service VALUES ('Residencia no-estudiantil1',1,1,1)
    INTO operator_spec VALUES ('Residencia no-estudiantil1', 100, 2, 'coordenadas1',1)
    INTO residence_spec VALUES ('Residencia no-estudiantil1', 10,0,'Descripcion de la residencia no-estudiantil1')
    INTO operator VALUES (7, 'Residencia no-estudiantil2', 'Residencia no-estudiantil')
    INTO operator_service VALUES ('Residencia no-estudiantil2',1,1,1)
    INTO operator_spec VALUES ('Residencia no-estudiantil2', 110, 3, 'coordenadas2',1)
    INTO residence_spec VALUES ('Residencia no-estudiantil2', 21,0,'Descripcion de la residencia no-estudiantil2')
    INTO operator VALUES (8, 'Residencia no-estudiantil3', 'Residencia no-estudiantil')
    INTO operator_service VALUES ('Residencia no-estudiantil3',1,1,1)
    INTO operator_spec VALUES ('Residencia no-estudiantil3', 120, 4, 'coordenadas3',1)
    INTO residence_spec VALUES ('Residencia no-estudiantil3', 32,0,'Descripcion de la residencia no-estudiantil3')
    INTO operator VALUES (9, 'Residencia no-estudiantil4', 'Residencia no-estudiantil')
    INTO operator_service VALUES ('Residencia no-estudiantil4',1,1,1)
    INTO operator_spec VALUES ('Residencia no-estudiantil4', 130, 5, 'coordenadas4',1)
    INTO residence_spec VALUES ('Residencia no-estudiantil4', 43,0,'Descripcion de la residencia no-estudiantil4')
    INTO operator VALUES (10, 'Residencia no-estudiantil5', 'Residencia no-estudiantil')
    INTO operator_service VALUES ('Residencia no-estudiantil5',1,1,1)
    INTO operator_spec VALUES ('Residencia no-estudiantil5', 140, 6, 'coordenadas5',1)
    INTO residence_spec VALUES ('Residencia no-estudiantil5', 54,0,'Descripcion de la residencia no-estudiantil5')
    INTO operator VALUES (11, 'Hostal1', 'Hostal')
    INTO operator_service VALUES ('Hostal1',1,1,1)
    INTO operator_spec VALUES ('Hostal1', 23, 1, 'coordenadas1',1)
    INTO hostel_spec VALUES ('Hostal1', 23, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('22:00:00', 'HH24:MI:SS'))
    INTO operator VALUES (12, 'Hostal2', 'Hostal')
    INTO operator_service VALUES ('Hostal2',1,1,1)
    INTO operator_spec VALUES ('Hostal2', 23, 1, 'coordenadas2',1)
    INTO hostel_spec VALUES ('Hostal2', 23, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('22:00:00', 'HH24:MI:SS'))
    INTO operator VALUES (13, 'Hostal3', 'Hostal')
    INTO operator_service VALUES ('Hostal3',1,1,1)
    INTO operator_spec VALUES ('Hostal3', 23, 1, 'coordenadas3',1)
    INTO hostel_spec VALUES ('Hostal3', 23, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('22:00:00', 'HH24:MI:SS'))
    INTO operator VALUES (14, 'Hostal4', 'Hostal')
    INTO operator_service VALUES ('Hostal4',1,1,1)
    INTO operator_spec VALUES ('Hostal4', 23, 1, 'coordenadas4',1)
    INTO hostel_spec VALUES ('Hostal4', 23, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('22:00:00', 'HH24:MI:SS'))
    INTO operator VALUES (15, 'Hostal5', 'Hostal')
    INTO operator_service VALUES ('Hostal5',1,1,1)
    INTO operator_spec VALUES ('Hostal5', 23, 1, 'coordenadas5',1)
    INTO hostel_spec VALUES ('Hostal5', 23, TO_TIMESTAMP('08:00:00', 'HH24:MI:SS'), TO_TIMESTAMP('22:00:00', 'HH24:MI:SS'))
    INTO operator VALUES (16, 'Habitacion de Hotel1', 'Habitacion de Hotel')
    INTO operator_service VALUES ('Habitacion de Hotel1',1,1,1)
    INTO operator_spec VALUES ('Habitacion de Hotel1', 100, 2, 'coordenadas1',1)
    INTO hotel_room_spec VALUES ('Habitacion de Hotel1', 10, 'Estandar', 1,1,1,50)
    INTO operator VALUES (17, 'Habitacion de Hotel2', 'Habitacion de Hotel')
    INTO operator_service VALUES ('Habitacion de Hotel2',1,1,1)
    INTO operator_spec VALUES ('Habitacion de Hotel2', 110, 2, 'coordenadas2',1)
    INTO hotel_room_spec VALUES ('Habitacion de Hotel2', 15, 'Estandar', 1,1,1,50)
    INTO operator VALUES (18, 'Habitacion de Hotel3', 'Habitacion de Hotel')
    INTO operator_service VALUES ('Habitacion de Hotel3',1,1,1)
    INTO operator_spec VALUES ('Habitacion de Hotel3', 100, 2, 'coordenadas3',1)
    INTO hotel_room_spec VALUES ('Habitacion de Hotel3', 20, 'Estandar', 1,1,1,50)
    INTO operator VALUES (19, 'Habitacion de Hotel4', 'Habitacion de Hotel')
    INTO operator_service VALUES ('Habitacion de Hotel4',1,1,1)
    INTO operator_spec VALUES ('Habitacion de Hotel4', 100, 2, 'coordenadas4',1)
    INTO hotel_room_spec VALUES ('Habitacion de Hotel4', 25, 'Estandar', 1,1,1,50)
    INTO operator VALUES (20, 'Habitacion de Hotel5', 'Habitacion de Hotel')
    INTO operator_service VALUES ('Habitacion de Hotel5',1,1,1)
    INTO operator_spec VALUES ('Habitacion de Hotel5', 100, 2, 'coordenadas5',1)
    INTO hotel_room_spec VALUES ('Habitacion de Hotel5', 40, 'Semi-suite', 1,1,1,50)
    INTO operator VALUES (21, 'Habitacion de casa1', 'Habitacion de casa')
    INTO operator_service VALUES ('Habitacion de casa1',1,1,1)
    INTO operator_spec VALUES ('Habitacion de casa1', 100, 2, 'coordenadas1',1)
    INTO house_room_spec VALUES ('Habitacion de casa1', 1,1)
    INTO operator VALUES (22, 'Habitacion de casa2', 'Habitacion de casa')
    INTO operator_service VALUES ('Habitacion de casa2',1,1,1)
    INTO operator_spec VALUES ('Habitacion de casa2', 100, 2, 'coordenadas2',1)
    INTO house_room_spec VALUES ('Habitacion de casa2', 1,1)
    INTO operator VALUES (23, 'Habitacion de casa3', 'Habitacion de casa')
    INTO operator_service VALUES ('Habitacion de casa3',1,1,1)
    INTO operator_spec VALUES ('Habitacion de casa3', 100, 2, 'coordenadas3',1)
    INTO house_room_spec VALUES ('Habitacion de casa3', 1,1)
    INTO operator VALUES (24, 'Habitacion de casa4', 'Habitacion de casa')
    INTO operator_service VALUES ('Habitacion de casa4',1,1,1)
    INTO operator_spec VALUES ('Habitacion de casa4', 100, 2, 'coordenadas4',1)
    INTO house_room_spec VALUES ('Habitacion de casa4', 1,1)
    INTO operator VALUES (25, 'Habitacion de casa5', 'Habitacion de casa')
    INTO operator_service VALUES ('Habitacion de casa5',1,1,1)
    INTO operator_spec VALUES ('Habitacion de casa5', 100, 2, 'coordenadas5',1)
    INTO house_room_spec VALUES ('Habitacion de casa5', 1,1)
    INTO operator VALUES (26, 'Apartamento1', 'Apartamento')
    INTO operator_service VALUES ('Apartamento1',1,1,1)
    INTO operator_spec VALUES ('Apartamento1', 75, 3, 'coordenadas1',1)
    INTO apartment_spec VALUES ('Apartamento1',1,1,0)
    INTO operator VALUES (27, 'Apartamento2', 'Apartamento')
    INTO operator_service VALUES ('Apartamento2',1,1,1)
    INTO operator_spec VALUES ('Apartamento2', 75, 3, 'coordenadas2',1)
    INTO apartment_spec VALUES ('Apartamento2',1,0,1)
    INTO operator VALUES (28, 'Apartamento3', 'Apartamento')
    INTO operator_service VALUES ('Apartamento3',1,1,1)
    INTO operator_spec VALUES ('Apartamento3', 75, 3, 'coordenadas3',1)
    INTO apartment_spec VALUES ('Apartamento3',1,1,2)
    INTO operator VALUES (29, 'Apartamento4', 'Apartamento')
    INTO operator_service VALUES ('Apartamento4',1,1,1)
    INTO operator_spec VALUES ('Apartamento4', 75, 3, 'coordenadas4',1)
    INTO apartment_spec VALUES ('Apartamento4',1,1,20)
    INTO operator VALUES (30, 'Apartamento5', 'Apartamento')
    INTO operator_service VALUES ('Apartamento5',1,1,1)
    INTO operator_spec VALUES ('Apartamento5', 75, 3, 'coordenadas5',1)
    INTO apartment_spec VALUES ('Apartamento5',1,1,0)
SELECT DUMMY FROM dual;

INSERT ALL
    INTO client VALUES (31, 'Cliente1', 'Estudiante')
    INTO client_preference VALUES (31, 1,1,1,1)
    INTO client VALUES (32, 'Cliente2', 'Estudiante Graduado')
    INTO client_preference VALUES (32, 1,1,1,0)
    INTO client VALUES (33, 'Cliente3', 'Empleado')
    INTO client_preference VALUES (33, 1,1,0,0)
    INTO client VALUES (34, 'Cliente4', 'Profesor')
    INTO client_preference VALUES (34, 1,0,0,0)
    INTO client VALUES (35, 'Cliente5', 'Familiar de estudiante')
    INTO client_preference VALUES (35, 1,1,0,1)
    INTO client VALUES (36, 'Cliente6', 'Profesor invitado')
    INTO client_preference VALUES (36, 1,0,1,1)
    INTO client VALUES (37, 'Cliente7', 'Invitado a evento')
    INTO client_preference VALUES (37, 1,0,0,1)
SELECT DUMMY FROM dual;

INSERT ALL
    INTO service_scheme VALUES ('Habitacion de casa1', 'Electricidad', 10)
    INTO service_scheme VALUES ('Habitacion de casa1', 'Agua', 15)
    INTO service_scheme VALUES ('Habitacion de casa1', 'Internet', 38)
    INTO service_scheme VALUES ('Habitacion de casa2', 'Cable', 20)
    INTO service_scheme VALUES ('Habitacion de casa2', 'Agua', 10)
    INTO service_scheme VALUES ('Habitacion de casa2', 'Internet', 60)
SELECT DUMMY FROM dual;

INSERT ALL
    INTO host_offer VALUES (1, 31, 'Habitacion de casa1', 25, TO_DATE('01/01/2021', 'DD/MM/YYYY'), TO_DATE('01/01/2022', 'DD/MM/YYYY'), 1, 1)
    INTO host_offer VALUES (2, 32, 'Habitacion de casa2', 2, TO_DATE('01/01/2021', 'DD/MM/YYYY'), TO_DATE('12/01/2021', 'DD/MM/YYYY'), 1, 1)
    INTO host_offer VALUES (3, 33, 'Residencia estudiantil1', 12, TO_DATE('01/01/2021', 'DD/MM/YYYY'), TO_DATE('01/06/2021', 'DD/MM/YYYY'), 1, 0)
    INTO host_offer VALUES (4, 34, 'Residencia estudiantil2', 8, TO_DATE('15/02/2023', 'DD/MM/YYYY'), TO_DATE('01/06/2023', 'DD/MM/YYYY'), 1, 0)
    INTO host_offer VALUES (5, 35, 'Hostal1', 4, TO_DATE('01/01/2021', 'DD/MM/YYYY'), TO_DATE('01/06/2021', 'DD/MM/YYYY'), 1, 0)
    INTO host_offer VALUES (6, 36, 'Hostal2', 3, TO_DATE('15/02/2023', 'DD/MM/YYYY'), TO_DATE('01/06/2023', 'DD/MM/YYYY'), 1, 1)
    INTO host_offer VALUES (7, 31, 'Habitacion de Hotel1', 6, TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('01/10/2022', 'DD/MM/YYYY'), 1, 0)
    INTO host_offer VALUES (8, 32, 'Habitacion de Hotel2', 5, TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('01/10/2022', 'DD/MM/YYYY'), 1, 1)
    INTO host_offer VALUES (9, 33, 'Habitacion de Hotel3', 5, TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('01/10/2022', 'DD/MM/YYYY'), 1, 1)
    INTO host_offer VALUES (10, 34, 'Habitacion de Hotel4', 5, TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('01/10/2022', 'DD/MM/YYYY'), 1, 1)
    INTO host_offer VALUES (11, 35, 'Habitacion de Hotel5', 5, TO_DATE('01/07/2022', 'DD/MM/YYYY'), TO_DATE('01/10/2022', 'DD/MM/YYYY'), 1, 1)
SELECT DUMMY FROM dual;

INSERT ALL
    INTO group_reservation VALUES (8, 1)
    INTO group_reservation VALUES (9, 1)
    INTO group_reservation VALUES (10, 1)
    INTO group_reservation VALUES (11, 1)
SELECT DUMMY FROM dual;